--[[--
Booklore Plugin Version Information

Auto-generated by generate-version.sh
DO NOT EDIT THIS FILE MANUALLY

@module koplugin.BookloreSync.version
--]]--

return {
    version = "0.0.0-dev+179f0b9",
    version_type = "development",
    git_commit = "179f0b9",
    build_date = "2026-02-11T16:37:13Z",
}
